import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const distDir = path.resolve(__dirname, '../dist');

// Read the base template generated by Vite
const templatePath = path.join(distDir, 'index.html');
if (!fs.existsSync(templatePath)) {
  console.log("Base dist/index.html does not exist yet. Run 'vite build' first.");
  process.exit(0);
}

const template = fs.readFileSync(templatePath, 'utf-8');

const routes = [
  {
    path: '',
    title: "D'Kingsfems Global Ltd | Premier International Travel, Tours & Study Placements",
    description: "Your trusted global travel partner for international & domestic flight tickets, corporate travel management, study abroad admissions, bespoke tours, and VIP escort security in Lagos, Nigeria.",
    heading: "D'Kingsfems Global Ltd — A Fifteen-Page Travel Platform Built to be Found, Trusted, and Booked From",
    intro: "Premier travel agency offering flight tickets, corporate travel, study abroad, tours and cruises, airport transfers, hotel bookings, escort cars, and conference management."
  },
  {
    path: 'about',
    title: "About Us | D'Kingsfems Global Ltd — Leading Travel & Education Agency",
    description: "Learn about D'Kingsfems Global Ltd, an accredited premier travel agency in Lagos, Nigeria specializing in global flights, study abroad admissions, and executive mobility.",
    heading: "About D'Kingsfems Global Ltd — Bridging You to the World with Integrity and Precision",
    intro: "D'Kingsfems Global Ltd is an accredited travel agency in Nigeria. We operate direct ticketing with leading international airlines and study placement partnerships with top universities across the UK, Canada, USA, and Europe."
  },
  {
    path: 'services',
    title: "Our 10 Dedicated Travel & Placement Services | D'Kingsfems Global Ltd",
    description: "Explore all ten dedicated services offered by D'Kingsfems Global Ltd: Flight tickets, corporate travel management, study abroad admissions, luxury tours, escort cars, and more.",
    heading: "Our Ten Core Travel & Placement Services",
    intro: "Full directory of specialized travel services including flight bookings, corporate travel accounts, study abroad advisory, luxury vacation tours, airport transfers, and VIP escort convoys."
  },
  {
    path: 'services/flight-tickets',
    title: "International & Domestic Flight Tickets | D'Kingsfems Global Ltd",
    description: "Book international and domestic flight tickets with D'Kingsfems Global Ltd. Enjoy best fares, direct airline booking, and 24/7 concierge support in Lagos, Nigeria.",
    heading: "International & Domestic Flight Tickets",
    intro: "Direct airline GDS access, negotiated business and economy fares, and instant reservation ticketing for international and domestic routes across British Airways, Qatar, Emirates, Delta, Air Peace, and more."
  },
  {
    path: 'services/corporate-travel',
    title: "Corporate Travel Management Services | D'Kingsfems Global Ltd",
    description: "Enterprise corporate travel management in Nigeria. Policy compliance, dedicated corporate account managers, consolidated billing, and VIP executive mobility.",
    heading: "Corporate Travel Management",
    intro: "Streamlined executive mobility, corporate policy compliance, consolidated monthly billing, and 24/7 emergency assistance for corporations, banks, and multinational delegations."
  },
  {
    path: 'services/airport-transfers',
    title: "Executive Airport Pick-Up & Drop-Off Services | D'Kingsfems Global",
    description: "Reliable VIP airport transfers in Lagos and Abuja. Meet-and-greet, luxury SUVs, real-time flight tracking, and vetted chauffeurs with D'Kingsfems Global.",
    heading: "Airport Pick-Up & Drop-Off",
    intro: "Punctual, comfortable, and executive airport transfers with real-time flight radar tracking, professional chauffeurs, and terminal meet-and-greet."
  },
  {
    path: 'services/tours-cruises',
    title: "Tours & Cruise Vacation Packages | D'Kingsfems Global Ltd",
    description: "Explore bespoke international tour packages and luxury cruise vacations with D'Kingsfems Global Ltd. Dubai, Zanzibar, Europe, Maldives, and Mediterranean sailings.",
    heading: "Tours & Cruises",
    intro: "Bespoke leisure packages, luxury cruise sailings, family holidays, honeymoon escapes, and exotic destination tours tailored to your dreams."
  },
  {
    path: 'services/hotel-bookings',
    title: "Global Hotel Bookings & Luxury Resorts | D'Kingsfems Global Ltd",
    description: "Book verified 3-star to 5-star hotels globally with D'Kingsfems Global Ltd. Competitive negotiated rates, embassy vouchers, and complimentary VIP amenities.",
    heading: "Hotel Bookings",
    intro: "Worldwide 3-star to 5-star hotel accommodations and luxury resort reservations at preferential negotiated rates with embassy-ready vouchers."
  },
  {
    path: 'services/study-abroad',
    title: "Study Abroad Consultants & University Admissions | D'Kingsfems Global",
    description: "Expert study abroad consulting in Nigeria. Secure admissions and student visas for UK, Canada, USA, and Europe universities with D'Kingsfems Global Ltd.",
    heading: "Study Abroad Advisory",
    intro: "Direct university admissions, statement of purpose guidance, scholarship assistance, and 98% student visa success across UK, Canada, USA, and Europe."
  },
  {
    path: 'services/jobs-abroad',
    title: "Jobs Abroad Consulting & Work Visa Advisory | D'Kingsfems Global",
    description: "Legitimate international employment advisory and skilled worker relocation guidance. Healthcare, engineering, and tech work permits with D'Kingsfems Global.",
    heading: "Jobs Abroad Advisory",
    intro: "Professional career consulting and work permit relocation advisory for qualified healthcare, tech, engineering, and skilled professionals."
  },
  {
    path: 'services/escort-cars',
    title: "Escort Cars & VIP Security Convoy Services | D'Kingsfems Global",
    description: "Executive escort cars and secure convoy logistics in Nigeria. Armed escorts, armored vehicles, and interstate VIP transit with D'Kingsfems Global Ltd.",
    heading: "Escort Cars (Intra & Interstate)",
    intro: "VIP armed and unarmed security convoys, armored vehicles (B6/B7 ballistic standards), and vetted security personnel for intra-state and inter-state journeys across Nigeria."
  },
  {
    path: 'services/conference-management',
    title: "Conference Management & Event Logistics | D'Kingsfems Global Ltd",
    description: "Premier conference management and summit logistics in Nigeria. International delegate travel, venue sourcing, AV production, and VIP protocol.",
    heading: "Conference Management",
    intro: "Turnkey corporate conference organization, international delegate travel logistics, venue procurement, and audiovisual production."
  },
  {
    path: 'services/school-excursions',
    title: "Educational School Excursions & Student Tours | D'Kingsfems Global",
    description: "Safe, curriculum-aligned school excursions in Nigeria and abroad. Insured student tours, certified guides, and educational adventures with D'Kingsfems Global.",
    heading: "School Excursions",
    intro: "Curriculum-aligned educational trips and student tours with strict child safety protocols, dedicated guides, and fully insured luxury transport."
  },
  {
    path: 'testimonials',
    title: "Client Testimonials & Reviews | D'Kingsfems Global Ltd",
    description: "Read verified client reviews and testimonials from corporate organizations, international students, and private travelers who partner with D'Kingsfems Global Ltd.",
    heading: "Client Stories & Testimonials",
    intro: "Verified testimonials from corporate clients, parents, international students, and leisure travelers who experience D'Kingsfems Global's world-class service."
  },
  {
    path: 'contact',
    title: "Contact Us | D'Kingsfems Global Ltd — Lagos Headquarters",
    description: "Connect with D'Kingsfems Global Ltd. Reach our flight desk, study abroad consultants, and corporate travel managers in Lagos, Nigeria via phone, WhatsApp, or email.",
    heading: "Contact D'Kingsfems Global Ltd",
    intro: "Visit our Victoria Island / Lekki headquarters or reach our 24/7 flight and study advisory desk via direct phone or WhatsApp."
  },
];

console.log("Generating static pre-rendered HTML files for SEO...");

routes.forEach((route) => {
  const targetDir = route.path ? path.join(distDir, route.path) : distDir;
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const canonicalUrl = `https://dkingsfemsglobal.com/${route.path}`;

  let html = template;
  
  // Replace title
  html = html.replace(/<title>.*?<\/title>/, `<title>${route.title}</title>`);
  
  // Replace meta description
  html = html.replace(
    /<meta name="description" content=".*?" \/>/,
    `<meta name="description" content="${route.description}" />`
  );
  
  // Replace canonical link
  html = html.replace(
    /<link rel="canonical" href=".*?" \/>/,
    `<link rel="canonical" href="${canonicalUrl}" />`
  );

  // Inject initial crawlable SSR content inside #root for search engines & bots
  const crawlableContent = `
    <div style="opacity: 0; pointer-events: none; position: absolute; left: -9999px;" aria-hidden="true">
      <h1>${route.heading}</h1>
      <p>${route.intro}</p>
      <nav>
        <a href="/">Home</a> |
        <a href="/about">About Us</a> |
        <a href="/services">Services</a> |
        <a href="/testimonials">Testimonials</a> |
        <a href="/contact">Contact</a>
      </nav>
    </div>
  `;

  html = html.replace('<div id="root"></div>', `<div id="root">${crawlableContent}</div>`);

  const filePath = path.join(targetDir, 'index.html');
  fs.writeFileSync(filePath, html, 'utf-8');
  console.log(`Pre-rendered: ${route.path ? `/${route.path}` : '/'} -> ${filePath}`);
});

console.log(`Successfully pre-rendered all ${routes.length} routes for SEO!`);
